# Generated by Django 3.0.4 on 2020-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murder_in_color', '0002_auto_20200306_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_id',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='user_id',
            field=models.CharField(default='----', max_length=50),
        ),
    ]
