CREATE TABLE public.murder_in_color_place (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description text NOT NULL,
    city_id integer NOT NULL
);

INSERT INTO public.murder_in_color_place VALUES
    (1,'Headquarters','This is the head office of Marshall Caleb Beckett. A jail is in the back. You hear the snores of a prisoner sleeping on a cot. Maps are on the wall behind the Marshall''s desk. A hat is laying on the desk. A gun case is in the corner.',1),
    (2,'Bank','The bank is strategically placed next to Headquarters. Employees count money behind a tall counter, in the background is a large black curtain. Sounds of change engulf the room. A small boy dumps his bag of coins for savings. Two windows are placed on either side of the central door.',1),
    (3,'Restaurant','You notice the fragrance of baked fish and salsa coming from the restaurant. Smells of freshly brewed coffee also invade your nose. You see a server with a large tray of drinks in her hand. Round tables are all around. Customers sit and wait for their food.',1),
    (4,'Hotel','The ding of a service bell rings in the hotel. Travelers wait in line for help. Room keys are hanging on nails behind the service desk. A pile of travel bags sit next to the door. You notice a couple grab their bags and head towards a wagon outside.',1),
    (5,'Saloon','Drunks stumble from the saloon. One hits the ground face first. Swinging doors open as people enter and exit. Benches are outside with a barrel next to the door. You see a bar with bottles set on shelves. You notice a round table with men around playing poker.',1),
    (6,'Barber','You see a striped pole outside the barber shop. A tolling church bell rings in the distance. You see a man with a beard. Shaving cream covers it. You hear the snipping of hair being cut. You see a man sitting on a chair waiting. He is reading a newspaper.',1),
    (7,'Cab','You come to the front of the train. A huge light is in the middle of it. Train horns blare as workers prepare for departure. Smoke billows out of the chimney. You see maps scattered on the driver''s desk for the journey ahead.',2),
    (8,'Blacksmith','You hear the loud bangs of a blacksmith hammering and reshaping a customer''s tool. You watch as sparks fly upward. There is a stable in the back. Horses stomp around making the place dusty. Horseshoes lay on a rack to be sold.',2),
    (9,'Depot','You notice a man checking train tickets at the depot. You hear dogs barking with excitement as they, along with other family members, give a proper farewell to the travelers. Passengers hurry along with bags in their hands. Children play while they wait to board.',2),
    (10,'Store','You see a building dedicated to refreshing the weary travelers. A couple sit at a table outside. An umbrella covers it. You see red pinstriped curtains lining a window. Candy, and other travel items are being displayed in the window. The door opens from time to time by anxious visitors.',2),
    (11,'Courthouse','You notice a row of pillars outside a courthouse. Steps come to a large central door where you see a sheriff leading a prisoner up the stairs. The prisoner struggles against his restraints. A statue of George Washington sits on the upper platform.',2),
    (12,'Caboose','You come to the the caboose. You see windows on the sides. Railroad workers pound at the inner joints of the train, securing the bolts in place. You notice iron rails on the back. A lantern is on board. A welded ladder leads to the train''s roof.',2),
    (13,'Bonfire','You are surrounded by tipis. You hear the sound of beating drums as Indians, both old and young, dance around a bonfire. You see an extravagant feather headdress on the ground.  Elders warm themselves by the fire. You appreciate the passionate yells as they pray to their ancestors for guidance.',3),
    (14,'Garden','You see a space dedicated to crops. You hear the wind whistling through the corn, and smell  the juicy onions. You notice a group of Indian ladies gardening, picking vegetables and putting  them in large baskets. Some ladies have baby slings, taking care of their young.',3),
    (15,'Tipi','You smell the aroma of herbs coming from this tent. You see billows of smoke coming from a pot on a small fire. A sick Indian is laying on a bed. A lantern is by his side. Covering the inside of the tipi  are colorful hand-crafted tapestries.',3),
    (16,'Lake','On a lake’s shore, you see piles of rocks. Several canoes are on the water. Indian elders teach their children how to fish. Other elders are showing young braves how to shoot rifles, which were traded by travelers. A section of beautiful sunflowers shine in the sunlight.',3),
    (17,'Forest','You stand on the edge of a forest. You can see many kinds of trees,
from the mighty oak to the pine. You find a group of horses tied to a tree. Young warriors shoot arrows with their bows, trying to hit trees they have defined as targets.',3),
    (18,'Spring','You come across sacred springs of water that spill onto the ground. You view an Indian as he fills his canteen. Around the springs are rings of stones. You feel small being surrounded by giant pine trees. You hear the songs of birds around you.',3),
    (19,'Creek','You notice many people flocked on the banks of a creek. The water is clear enough to see rocks on the bottom.  You find gold pans scattered on the coasts of the stream. All around,  there are patches of cacti and yucca plants.',4),
    (20,'Wagons','A group of wagons is stopped. A man and his wife get ready for lunch, cooking on a campfire. You smell freshly baked beans, chicken, and rice. The sound of a team of horses rings as they are being cared for. A lantern sits on the back of a wagon.',4),
    (21,'Cabin','You come to a little wood cabin. A pile of sticks is at the side of the house. There is an axe stuck in a stump for chopping wood. You see smoke billowing out of the chimney. You notice a man working hard building a fence.',4),
    (22,'Meadow','You see a meadow up ahead. It comes alive with color as you notice a field of flowers, from sunflowers to lilies. Bees buzz as they go from flower to flower. The sounds of kids playing in the green grass ring in your ears.',4),
    (23,'Pond','You stumble upon a small pond. You hear croaks of frogs that live there. You smell seaweed and other minerals in the water. You notice a trail of compacted plants created by years of migrating animals. You find sun-bleached antlers laying on the ground.',4),
    (24,'Mine','You notice a large mine with stalagmites at its entrance. You hear the  fluttering of bats as men pick away at the rock for their prize gold nugget. You see a cart and railroad tracks nearby as you  feel a strong breeze coming from the mine''s entrance.',4),
    (25,'Outpost','You approach a hot campfire. Soldiers, sitting on stumps and rocks, huddle around it. You smell the fragrance of roasting coffee. You are engulfed in a plum of smoke. Other soldiers are on high alert keeping guard. They have rifles on their shoulders, ready for action at any moment.',5),
    (26,'Barracks','You come across the main housing for soldiers. Lines of small wood buildings are in view. You hear the sounds of troopers walking about with their families. A church bell rings in the distance. Dust flies up from the ground from the busyness around you.',5),
    (27,'Bridge','You come across a beautiful  bridge. You see people around enjoying the scenery of both  plant life and animal life. The bridge is made from smooth stones, and built  over a slow-moving river. You notice a lantern  resting on the side of the bridge.',5),
    (28,'Command','You come to the command office of the army captain. You hear a choir of crickets singing nearby. You notice a compass on a desk. Maps are hung on the wall behind it. An officer''s coat and hat are next to the door.',5),
    (29,'Corral','You see a fenced area with a group of horses inside. The sound of neighing surrounds you. A soldier on a horse riding away. There is a trough with a man pouring water into it, while horses drink from it. A gate with a padlock keeps this area secure.',5),
    (30,'Range','You see men lined up to shoot targets. Their low-powered rifles rest on sandbags for better aim. You hear shots ringing out as the red targets move with every hit. You smell the distinct odor of gunpowder. You notice a man at a nearby table cleaning his gun.',5);
