CREATE TABLE public.murder_in_color_responses (
    id integer NOT NULL,
    suspect text NOT NULL,
    place text NOT NULL,
    weapon text NOT NULL,
    goodbye text NOT NULL,
    witness_id integer NOT NULL
);

INSERT INTO public.murder_in_color_responses VALUES
    (1,'He was as tall as the trees!','He had dried mud on his boots.','I am sorry, I did not notice anything.','I hope you find the crook soon!',1),
    (2,'He was head and shoulders above everyone.','He mentioned how he loved horses.','I did not notice anything out of the ordinary.','Have a wonderful day!',2),
    (3,'He was as thin as a bacon slice.','He said he was around water.','Everything was ok from my perspective.','Good day!',3),
    (4,'He is as thin as I am.','He mentioned that he was warming himself by a fire.','Everything was alright to me.','Good Luck!',4),
    (5,'You would need at least two of him to make a shadow.','"Smoke follows beauty", he kept saying.','I didn''t see anything.','Safe travels!',5),
    (6,'We could see eye to eye.','He noticed the sound of neighing.','I don''t know anything about that, sorry.','You have a splendid day.',6),
    (7,'I looked up to him.','He never mentioned any places he visited.','I saw him get on the train with something with a handle.','Take it easy!',7),
    (8,'He was a giant.','I cannot add anything new about it.','I noticed one of my tools went missing right after he visited.','I hope you catch him!',8),
    (9,'If I did an eyebrow battle with his, we would be evenly matched.','I did not hear anything about that.','He was carrying around a banging instrument.','Take care!',9),
    (10,'He had a large umbrella over his eyes.','I cannot add any extra information on the place.','He could have used the tool to fasten the table together.','Farewell!',10),
    (11,'I wondered how many doorways he ran into.','That never came up in our conversation.','I noticed the head of it sticking out of a bag.','Be blessed!',11),
    (12,'Forehead sweat would never reach his eyes.','I cannot comment on this.','I thought I saw a T shaped item in a bag.','I wish you the best!',12),
    (13,'He would fit in well here.','He commented about how well their aim was.','If he had one, I did not see it.','See you later!',13),
    (14,'I asked him if he was from around here.','He mentioned hearing crickets in the night.','There was nothing I noticed.','Have a great rest of your day!',14),
    (15,'There was not much to him.','He mentioned how he loved the smell of coffee.','I didn''t see anything to make me question him.','Wonderful day!',15),
    (16,'He could fit through a large crack easily.','He said he had helped gather wood for a fire nearby.','If I knew anything, I would tell you.','Bye!',16),
    (17,'He showed me his war cry.','He talked about hearing gunshots','I found nothing in his hands.','Have a good trip!',17),
    (18,'If the wind blew, he would have been swept away.','He mentioned a bell he heard.','I did not notice anything suspicious.','Don''t worry about!',18),
    (19,'He was as tall as me.','He mentioned something about a group of rocks.','Everything seemed normal to me.','I am glad to help!',19),
    (20,'I would have to stand on myself to get a good look at his face.','He was telling me how smooth the rocks were over there.','I didn''t see any weapon.','I wish there was more I could do!',20),
    (21,'I have a sore neck after talking to him.','He said he sat on a stone there.','I cannot speak on this.','Have a great day ahead!',21),
    (22,'His eyebrows could rival a bush.','I saw him doing something quite strange there. He had asked me if I had a match, because the light went out.','I have nothing odd to report about that.','No Problem!',22),
    (23,'He had a lot of hair, and it wasn''t on top.','"The fire was quite blinding!", he said.','I saw nothing special.','I wish you well!',23),
    (24,'The thing that stood out to me was his eyebrows.','He was telling me how well the fire was built.','I did not hear anything about that!','Adios!',24),
    (25,'His hair was the color of coal.','He did not mention anything about where he had been.','I cannot help you with that.','I hope you find him soon!',25),
    (26,'He bragged how good he was with a bow and arrow.','I cannot remember anything about the place he mentioned.','I am sorry, I cannot give you a definite answer.','Goodbye!',26),
    (27,'I thought I saw some ribs on the man.','I could not give you any details about the location.','I did not hear anything about that.','I hope you find who you are looking for!',27),
    (28,'His hair blended into the night sky like mine.','I do not recall anything.','Nothing comes to mind.','If I think of any more information, I will let you know!',28),
    (29,'He mentioned he had to get something from his tent.','I cannot help you, unfortunately.','I forget what he mentioned about that.','I wish I could have assisted more!',29),
    (30,'I was surprised to see someone else as thin as me.','No information on the place to report.','I couldn''t be sure about any weapon.','I hope everything turns out alright!',30);
