# Generated by Django 3.0.4 on 2020-06-17 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='----', max_length=50)),
                ('theme', models.CharField(default='----', max_length=50)),
                ('description', models.TextField()),
                ('travel_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='----', max_length=50)),
                ('gender', models.CharField(default='----', max_length=50)),
                ('race', models.CharField(default='----', max_length=50)),
                ('height', models.CharField(default='----', max_length=50)),
                ('age', models.CharField(default='----', max_length=50)),
                ('weight', models.CharField(default='----', max_length=50)),
                ('hair_color', models.CharField(default='----', max_length=50)),
                ('face_feature', models.CharField(default='----', max_length=50)),
                ('unique_feature', models.CharField(default='----', max_length=50)),
                ('crime_place', models.CharField(default='----', max_length=50)),
                ('weapon', models.CharField(default='----', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='----', max_length=50)),
                ('description', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murder_in_color.City')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='----', max_length=50)),
                ('rank', models.CharField(default='----', max_length=50)),
                ('name', models.CharField(default='----', max_length=50)),
                ('description', models.TextField()),
                ('question_suspect', models.CharField(default='----', max_length=50)),
                ('question_place', models.CharField(default='----', max_length=50)),
                ('question_weapon', models.CharField(default='----', max_length=50)),
                ('goodbye', models.CharField(default='----', max_length=50)),
                ('place_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='----', max_length=50)),
                ('description', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murder_in_color.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect', models.TextField()),
                ('place', models.TextField()),
                ('weapon', models.TextField()),
                ('goodbye', models.TextField()),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murder_in_color.Witness')),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='----', max_length=50)),
                ('description', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murder_in_color.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='----', max_length=50)),
                ('case_name', models.CharField(default='----', max_length=50)),
                ('days_left', models.IntegerField()),
                ('evidence', models.IntegerField()),
                ('signatures', models.IntegerField()),
                ('warrant', models.BooleanField()),
                ('name', models.CharField(default='----', max_length=50)),
                ('gender', models.CharField(default='----', max_length=50)),
                ('race', models.CharField(default='----', max_length=50)),
                ('height', models.CharField(default='----', max_length=50)),
                ('age', models.CharField(default='----', max_length=50)),
                ('weight', models.CharField(default='----', max_length=50)),
                ('hair_color', models.CharField(default='----', max_length=50)),
                ('face_feature', models.CharField(default='----', max_length=50)),
                ('unique_feature', models.CharField(default='----', max_length=50)),
                ('crime_place', models.CharField(default='----', max_length=50)),
                ('weapon', models.CharField(default='----', max_length=50)),
                ('notebook', models.TextField()),
                ('solved', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murder_in_color.Player')),
            ],
        ),
    ]
