# Generated by Django 2.2.6 on 2019-11-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('travel_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('race', models.CharField(max_length=40)),
                ('height', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=40)),
                ('weight', models.CharField(max_length=40)),
                ('hair_color', models.CharField(max_length=40)),
                ('face_feature', models.CharField(max_length=40)),
                ('unique_feature', models.CharField(max_length=40)),
                ('crime_place', models.CharField(max_length=40)),
                ('weapon', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mic.City')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('place', models.TextField()),
                ('weapon', models.TextField()),
                ('goodbye', models.TextField()),
                ('place_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('days_left', models.IntegerField()),
                ('evidence', models.IntegerField()),
                ('warrant', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mic.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect', models.TextField()),
                ('place', models.TextField()),
                ('weapon', models.TextField()),
                ('goodbye', models.TextField()),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mic.Witness')),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mic.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('race', models.CharField(max_length=40)),
                ('height', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=40)),
                ('weight', models.CharField(max_length=40)),
                ('hair_color', models.CharField(max_length=40)),
                ('face_feature', models.CharField(max_length=40)),
                ('unique_feature', models.CharField(max_length=40)),
                ('crime_place', models.CharField(max_length=40)),
                ('weapon', models.CharField(max_length=40)),
                ('solved', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mic.Player')),
            ],
        ),
    ]
