# Generated by Django 2.2.6 on 2019-11-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='place',
        ),
        migrations.RemoveField(
            model_name='player',
            name='weapon',
        ),
        migrations.AddField(
            model_name='player',
            name='question_place',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='question_suspect',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='question_weapon',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='age',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_name',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='crime_place',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='face_feature',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='gender',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='hair_color',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='height',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='race',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='unique_feature',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='weapon',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='weight',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='clue',
            name='name',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='age',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='crime_place',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='face_feature',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='gender',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='hair_color',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='height',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='name',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='race',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='unique_feature',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='weapon',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='weight',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='goodbye',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AlterField(
            model_name='witness',
            name='name',
            field=models.CharField(default='----', max_length=50),
        ),
    ]
